# fly.toml app configuration file generated for fantatimer-be on 2025-09-08T09:45:13Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fantatimer-be'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
